-- SELECT * FROM item ORDER BY item_price ASC
-- SELECT * FROM item WHERE item_price >= 80 ORDER BY item_price DESC
-- SELECT first_name, last_name from customers  ORDER BY first_name ASC LIMIT 3
-- SELECT last_name from customers ORDER BY last_name DESC